task_5/task_5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls", namespace='users'))
]

task_5/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete')
]

task_5/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    username = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.username

task_5/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput())
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class UserUpdateForm(UserChangeForm):
    username = forms.CharField(label='Login', widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'password')

task_5/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import User
from .forms import UserLoginForm, UserRegisterForm, UserUpdateForm

def index(request):
    return render(request, 'index.html')

def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserLoginForm()
    context = {
        "form": form
    }
    return render(request, 'login.html', context)

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Успешная регистрация!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegisterForm()
    context = {
        'form': form
    }
    return render(request, 'register.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:index'))

@login_required
def profile(request):
    return render(request, 'profile.html', {'user': request.user})

@login_required
def update(request):
    if request.method == "POST":
        form = UserUpdateForm(data=request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            new_password = form.cleaned_data.get('password')
            if new_password:
                user.set_password(new_password)
            user.save()
            messages.success(request, 'Успешное изменение!')
            auth.update_session_auth_hash(request, user)
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserUpdateForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'update.html', context)

@login_required
def delete(request):
    user = request.user
    user.delete()
    return HttpResponseRedirect(reverse('users:index'))

task_5/users/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Base</title>
</head>
<body>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block content %}{% endblock %}
</body>
</html>

task_5/users/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Index</title>
</head>
<body>
    <button><a href="{% url 'users:login' %}">Войти</a></button>
</body>
</html>

task_5/users/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Вход</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
        <button><a href="{% url 'users:register' %}">Зарегистрироваться</a></button>
    </form>
{% endblock %}

task_5/users/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>Привет, {{ user.username }}</h1>
    <button><a href="{% url 'users:update' %}">Изменить данные</a></button>
    <button><a href="{% url 'users:logout' %}">Выйти</a></button>
{% endblock %}

task_5/users/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
        <button><a href="{% url 'users:login' %}">Войти</a></button>
    </form>
{% endblock %}

task_5/users/templates/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Отредактировать</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Изменить</button>
        <button><a href="{% url 'users:delete' %}">Удалить</a></button>
        <button><a href="{% url 'users:profile' %}">Назад</a></button>
    </form>
{% endblock %}